/* dati/mosse.js — Database mosse Gen 1-3 (generato da docs/MOSSE_GEN1_3.md)
   Categorie: "fisico" | "speciale" | "stato"
   potenza/accuratezza = 0 quando non applicabile (mosse di stato).
   effetto = codice snake_case gestito in battle.js (null se nessun effetto). */

const MOSSE_DB = {
  1: { nome:"Rinforzo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"alza_atk_2", descrizione:"Aumenta l'Attacco del bersaglio di 2 stadi." },
  2: { nome:"Avvinghia", tipo:"normal", cat:"fisico", potenza:15, accuratezza:85, pp:20, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno. Intrappola il bersaglio." },
  3: { nome:"Crescita", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"alza_spa_1", descrizione:"Aumenta l'Attacco Speciale e la Difesa Speciale di 1 stadio." },
  4: { nome:"Taglio Foglia", tipo:"grass", cat:"fisico", potenza:35, accuratezza:95, pp:25, effetto:"abbassa_dif_1", descrizione:"Può far abbassare la Difesa del bersaglio." },
  5: { nome:"Grandinata", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Infligge danno in base all'età del bersaglio." },
  6: { nome:"Dissolvisole", tipo:"fire", cat:"speciale", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Potenzia le mosse di tipo Fuoco per 5 turni." },
  7: { nome:"Doppio Calcio", tipo:"fighting", cat:"fisico", potenza:30, accuratezza:100, pp:30, effetto:"colpisce_due", descrizione:"Colpisce due volte nello stesso turno." },
  8: { nome:"Doppio Artiglio", tipo:"normal", cat:"fisico", potenza:15, accuratezza:85, pp:30, effetto:"colpisce_due", descrizione:"Colpisce due volte nello stesso turno." },
  9: { nome:"Doppio Morso", tipo:"dark", cat:"fisico", potenza:15, accuratezza:85, pp:30, effetto:"colpisce_due", descrizione:"Colpisce due volte nello stesso turno." },
  10: { nome:"Occhiocupo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"abbassa_eva_1", descrizione:"Abbassa l'Evasività del bersaglio di 1 stadio." },
  11: { nome:"Sferracalci", tipo:"fighting", cat:"fisico", potenza:50, accuratezza:100, pp:25, effetto:null, descrizione:"Sempre efficace." },
  12: { nome:"Rasoiovento", tipo:"normal", cat:"speciale", potenza:40, accuratezza:95, pp:25, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  13: { nome:"Raggio Confusione", tipo:"psychic", cat:"speciale", potenza:50, accuratezza:100, pp:25, effetto:"confusione_10", descrizione:"10% di probabilità di confondere il bersaglio." },
  14: { nome:"Taglio", tipo:"normal", cat:"fisico", potenza:50, accuratezza:95, pp:30, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  15: { nome:"Tagliavento", tipo:"flying", cat:"speciale", potenza:40, accuratezza:100, pp:35, effetto:null, descrizione:"Colpisce anche i bersagli che usano Volo." },
  16: { nome:"Trasformazione", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Si trasforma nel Pokémon bersaglio copiando tutte le statistiche." },
  17: { nome:"Bolla", tipo:"water", cat:"speciale", potenza:20, accuratezza:100, pp:30, effetto:"abbassa_vel_1", descrizione:"10% di probabilità di abbassare la Velocità del bersaglio." },
  18: { nome:"Acqua Pistola", tipo:"water", cat:"speciale", potenza:40, accuratezza:100, pp:25, effetto:null, descrizione:"Nessun effetto secondario." },
  19: { nome:"Tempobolla", tipo:"water", cat:"speciale", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_vel_1", descrizione:"10% di probabilità di abbassare la Velocità del bersaglio." },
  20: { nome:"Idropompa", tipo:"water", cat:"speciale", potenza:110, accuratezza:80, pp:5, effetto:null, descrizione:"Nessun effetto secondario." },
  21: { nome:"Rapidità", tipo:"flying", cat:"fisico", potenza:40, accuratezza:100, pp:35, effetto:"priorita_p1", descrizione:"Va sempre per primo (priorità +1)." },
  22: { nome:"Turbine", tipo:"flying", cat:"speciale", potenza:40, accuratezza:100, pp:15, effetto:"confusione_10", descrizione:"Può confondere il bersaglio." },
  23: { nome:"Volo", tipo:"flying", cat:"fisico", potenza:90, accuratezza:95, pp:15, effetto:"due_turni_volo", descrizione:"Il turno 1 il user vola alto; il turno 2 colpisce." },
  24: { nome:"Costrizione", tipo:"normal", cat:"fisico", potenza:15, accuratezza:75, pp:20, effetto:"intrappola", descrizione:"Intrappola il bersaglio per 4-5 turni." },
  25: { nome:"Artiglioveleno", tipo:"poison", cat:"fisico", potenza:15, accuratezza:100, pp:35, effetto:"veleno_30", descrizione:"Può avvelenare il bersaglio (probabilità 30%)." },
  26: { nome:"Puntura Venefica", tipo:"poison", cat:"fisico", potenza:15, accuratezza:100, pp:35, effetto:"veleno_30", descrizione:"Può avvelenare il bersaglio (probabilità 30%)." },
  27: { nome:"Sferzata Acida", tipo:"poison", cat:"speciale", potenza:40, accuratezza:100, pp:30, effetto:"abbassa_spd_1", descrizione:"Può abbassare la Difesa Speciale del bersaglio." },
  28: { nome:"Acido Corrosivo", tipo:"poison", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:"abbassa_spd_1", descrizione:"Può abbassare la Difesa Speciale del bersaglio." },
  29: { nome:"Morso Velenoso", tipo:"poison", cat:"fisico", potenza:35, accuratezza:100, pp:15, effetto:"veleno_30", descrizione:"30% di probabilità di avvelenare il bersaglio." },
  30: { nome:"Aculei Velenosi", tipo:"poison", cat:"fisico", potenza:15, accuratezza:100, pp:35, effetto:"veleno_30", descrizione:"Può avvelenare il bersaglio." },
  31: { nome:"Fissatore", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:30, effetto:"abbassa_acc_1", descrizione:"Abbassa l'Accuratezza del bersaglio di 1 stadio." },
  32: { nome:"Nuvola Nebbiosa", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"abbassa_acc_1", descrizione:"Abbassa l'Accuratezza di tutti i Pokémon in campo di 1 stadio." },
  33: { nome:"Mannaia", tipo:"normal", cat:"fisico", potenza:80, accuratezza:80, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio se non colpisce." },
  34: { nome:"Colpo Basso", tipo:"normal", cat:"fisico", potenza:40, accuratezza:100, pp:35, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  35: { nome:"Vibrazione", tipo:"normal", cat:"fisico", potenza:20, accuratezza:100, pp:20, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio causandone la paralisi." },
  36: { nome:"Danza Spade", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_2", descrizione:"Aumenta l'Attacco dell'utente di 2 stadi." },
  37: { nome:"Forbici X", tipo:"bug", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  38: { nome:"Taglioerba", tipo:"grass", cat:"fisico", potenza:55, accuratezza:95, pp:25, effetto:"abbassa_dif_1", descrizione:"Può abbassare la Difesa del bersaglio." },
  39: { nome:"Forzavento", tipo:"flying", cat:"speciale", potenza:55, accuratezza:100, pp:15, effetto:"confusione_10", descrizione:"Può confondere il bersaglio." },
  40: { nome:"Nodo Veleno", tipo:"grass", cat:"fisico", potenza:45, accuratezza:85, pp:15, effetto:"veleno_100", descrizione:"100% di probabilità di avvelenare il bersaglio." },
  41: { nome:"Martello a Punta", tipo:"steel", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio di 1 stadio." },
  42: { nome:"Pugni Pazzo", tipo:"normal", cat:"fisico", potenza:20, accuratezza:85, pp:20, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  43: { nome:"Furia", tipo:"normal", cat:"fisico", potenza:15, accuratezza:85, pp:20, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  44: { nome:"Sonnifero", tipo:"grass", cat:"stato", potenza:0, accuratezza:55, pp:15, effetto:"sonno", descrizione:"Addormenta il bersaglio." },
  45: { nome:"Polvere Sonnifero", tipo:"grass", cat:"stato", potenza:0, accuratezza:75, pp:15, effetto:"sonno", descrizione:"Addormenta il bersaglio." },
  46: { nome:"Velenpolvere", tipo:"poison", cat:"stato", potenza:0, accuratezza:75, pp:35, effetto:"veleno_100", descrizione:"Avvelena il bersaglio." },
  47: { nome:"Paralisipolvere", tipo:"electric", cat:"stato", potenza:0, accuratezza:75, pp:30, effetto:"paralisi_100", descrizione:"Paralizza il bersaglio." },
  48: { nome:"Ruba Sonno", tipo:"psychic", cat:"speciale", potenza:0, accuratezza:100, pp:15, effetto:null, descrizione:"Toglie sonno al bersaglio e assorbe PV (50% inflitti)." },
  49: { nome:"Assorbisogni", tipo:"psychic", cat:"speciale", potenza:0, accuratezza:100, pp:15, effetto:"sonno", descrizione:"Assorbe i sogni del bersaglio addormentato. Recupera PV." },
  50: { nome:"Vento Gelido", tipo:"ice", cat:"speciale", potenza:55, accuratezza:95, pp:15, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  51: { nome:"Filo Seta", tipo:"bug", cat:"stato", potenza:0, accuratezza:100, pp:40, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità del bersaglio di 1 stadio." },
  52: { nome:"Lancio Filo", tipo:"bug", cat:"fisico", potenza:50, accuratezza:95, pp:35, effetto:null, descrizione:"Nessun effetto secondario." },
  53: { nome:"Bruciapelo", tipo:"fire", cat:"speciale", potenza:40, accuratezza:100, pp:25, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  54: { nome:"Brace", tipo:"fire", cat:"speciale", potenza:65, accuratezza:100, pp:15, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  55: { nome:"Fiamma", tipo:"fire", cat:"speciale", potenza:70, accuratezza:100, pp:15, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  56: { nome:"Lanciafiamme", tipo:"fire", cat:"speciale", potenza:90, accuratezza:100, pp:15, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  57: { nome:"Bagliore di Fuoco", tipo:"fire", cat:"speciale", potenza:120, accuratezza:85, pp:5, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  58: { nome:"Colpo Fuoco", tipo:"fire", cat:"speciale", potenza:110, accuratezza:85, pp:5, effetto:"ustione_30", descrizione:"30% di probabilità di ustionare il bersaglio." },
  59: { nome:"Fuocobolla", tipo:"fire", cat:"speciale", potenza:40, accuratezza:100, pp:25, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  60: { nome:"Onda d'Urto", tipo:"normal", cat:"speciale", potenza:40, accuratezza:100, pp:20, effetto:"paralisi_30", descrizione:"Può paralizzare il bersaglio." },
  61: { nome:"Tuono", tipo:"electric", cat:"speciale", potenza:110, accuratezza:70, pp:10, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  62: { nome:"Fulmine", tipo:"electric", cat:"speciale", potenza:90, accuratezza:100, pp:15, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  63: { nome:"Folgore", tipo:"electric", cat:"speciale", potenza:40, accuratezza:100, pp:30, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  64: { nome:"Tonnellata", tipo:"normal", cat:"fisico", potenza:120, accuratezza:75, pp:5, effetto:"paralisi_30", descrizione:"Può far rabbrividire il bersaglio." },
  65: { nome:"Terremoto", tipo:"ground", cat:"fisico", potenza:100, accuratezza:100, pp:10, effetto:null, descrizione:"Colpisce anche i Pokémon che usano Scavata." },
  66: { nome:"Frana", tipo:"ground", cat:"fisico", potenza:75, accuratezza:90, pp:10, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio." },
  67: { nome:"Spintone", tipo:"ground", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:null, descrizione:"Il bersaglio viene scaraventato via." },
  68: { nome:"Lancio", tipo:"normal", cat:"fisico", potenza:50, accuratezza:90, pp:10, effetto:null, descrizione:"Lancia il bersaglio contro un avversario." },
  69: { nome:"Roccia Tombale", tipo:"rock", cat:"fisico", potenza:75, accuratezza:90, pp:10, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio." },
  70: { nome:"Scossa di Roccia", tipo:"rock", cat:"fisico", potenza:50, accuratezza:80, pp:15, effetto:"abbassa_spd_1", descrizione:"Può abbassare la Difesa Speciale del bersaglio." },
  71: { nome:"Scavatana", tipo:"ground", cat:"fisico", potenza:80, accuratezza:100, pp:10, effetto:"due_turni_scavata", descrizione:"Il turno 1 scava; il turno 2 colpisce." },
  72: { nome:"Avalanga", tipo:"rock", cat:"fisico", potenza:75, accuratezza:90, pp:10, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio." },
  73: { nome:"Macigno", tipo:"rock", cat:"fisico", potenza:100, accuratezza:75, pp:5, effetto:"paralisi_30", descrizione:"30% di probabilità di far tremare il bersaglio." },
  74: { nome:"Mina", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_dif_1", descrizione:"Aumenta la Difesa dell'utente di 1 stadio." },
  75: { nome:"Guscio Difesa", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"alza_spd_1", descrizione:"Aumenta Difesa e Difesa Speciale dell'utente di 1 stadio." },
  76: { nome:"Difesa Ferrea", tipo:"steel", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:"alza_dif_2", descrizione:"Aumenta la Difesa dell'utente di 2 stadi." },
  77: { nome:"Blocco", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:"intrappola", descrizione:"Intrappola il bersaglio impedendogli di fuggire." },
  78: { nome:"Occhioduro", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:30, effetto:"abbassa_atk_1", descrizione:"Abbassa l'Attacco del bersaglio di 1 stadio." },
  79: { nome:"Balena", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"alza_eva_1", descrizione:"Aumenta l'Evasività dell'utente di 1 stadio." },
  80: { nome:"Danzatuono", tipo:"electric", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_1", descrizione:"Aumenta l'Attacco e la Velocità dell'utente di 1 stadio." },
  81: { nome:"Scheggia di Ghiaccio", tipo:"ice", cat:"fisico", potenza:40, accuratezza:100, pp:30, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  82: { nome:"Vento di Ghiaccio", tipo:"ice", cat:"speciale", potenza:55, accuratezza:95, pp:15, effetto:"abbassa_vel_1", descrizione:"10% di probabilità di abbassare la Velocità del bersaglio." },
  83: { nome:"Buffera", tipo:"ice", cat:"speciale", potenza:95, accuratezza:90, pp:10, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  84: { nome:"Surf", tipo:"water", cat:"speciale", potenza:90, accuratezza:100, pp:15, effetto:null, descrizione:"Colpisce tutti i Pokémon in campo. Può fare doppio danno a chi usa Tuffo." },
  85: { nome:"Laccio Erboso", tipo:"grass", cat:"stato", potenza:0, accuratezza:55, pp:20, effetto:"intrappola", descrizione:"Intrappola il bersaglio infliggendo danno per 4-5 turni." },
  86: { nome:"Ipnotismo", tipo:"psychic", cat:"stato", potenza:0, accuratezza:60, pp:20, effetto:"sonno", descrizione:"Addormenta il bersaglio." },
  87: { nome:"Psico Luce", tipo:"psychic", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"abbassa_spa_1", descrizione:"Abbassa l'Attacco Speciale e la Difesa Speciale di tutti i nemici di 1 stadio." },
  88: { nome:"Psicocinetica", tipo:"psychic", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:"abbassa_spd_1", descrizione:"10% di probabilità di abbassare la Difesa Speciale del bersaglio." },
  89: { nome:"Raggio Psico", tipo:"psychic", cat:"speciale", potenza:65, accuratezza:100, pp:10, effetto:"due_turni_carica", descrizione:"Richiede 1 turno di carica, poi colpisce." },
  90: { nome:"Telecinesi", tipo:"psychic", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Lancia un oggetto al bersaglio. Forza al colpo." },
  91: { nome:"Recupero", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"cura_meta", descrizione:"Recupera metà dei PV massimi dell'utente." },
  92: { nome:"Assorbimento", tipo:"grass", cat:"speciale", potenza:20, accuratezza:100, pp:25, effetto:"assorbi_50", descrizione:"Assorbe PV pari al 50% del danno inflitto." },
  93: { nome:"Megaassorbimento", tipo:"grass", cat:"speciale", potenza:40, accuratezza:100, pp:15, effetto:"assorbi_50", descrizione:"Assorbe PV pari al 50% del danno inflitto." },
  94: { nome:"Gigaassorbimento", tipo:"grass", cat:"speciale", potenza:60, accuratezza:100, pp:5, effetto:"assorbi_50", descrizione:"Assorbe PV pari al 50% del danno inflitto." },
  95: { nome:"Luce del Giorno", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:"cura_meta", descrizione:"Recupera tutti i PV. L'effetto varia col meteo." },
  96: { nome:"Luna Splendente", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:"cura_meta", descrizione:"Recupera PV. L'effetto varia col meteo." },
  97: { nome:"Ovoassorbimento", tipo:"normal", cat:"speciale", potenza:40, accuratezza:100, pp:10, effetto:"assorbi_50", descrizione:"Assorbe PV pari al 50% del danno inflitto." },
  98: { nome:"Assorbisalute", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"cura_meta", descrizione:"Recupera PV drenando la vitalità del bersaglio." },
  99: { nome:"Azione", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"alza_acc_1", descrizione:"Aumenta l'Accuratezza dell'utente di 1 stadio." },
  100: { nome:"Urlo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"abbassa_atk_2", descrizione:"Abbassa l'Attacco del bersaglio di 2 stadi." },
  101: { nome:"Supersonic", tipo:"normal", cat:"stato", potenza:0, accuratezza:55, pp:20, effetto:"confusione_10", descrizione:"Confonde il bersaglio." },
  102: { nome:"Specchio", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Riflette le mosse di stato sul bersaglio." },
  103: { nome:"Sbadiglio", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"sonno", descrizione:"Al turno successivo addormenta il bersaglio." },
  104: { nome:"Urocanto", tipo:"normal", cat:"stato", potenza:0, accuratezza:55, pp:15, effetto:"abbassa_atk_2", descrizione:"Abbassa l'Attacco di tutti i nemici di 2 stadi." },
  105: { nome:"Sibilosacro", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale del bersaglio di 2 stadi." },
  106: { nome:"Ululato", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:"abbassa_spa_1", descrizione:"Abbassa l'Attacco Speciale del bersaglio di 1 stadio." },
  107: { nome:"Ruglitotuono", tipo:"electric", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"paralisi_100", descrizione:"Paralizza tutti i nemici." },
  108: { nome:"Miniaturizza", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_eva_2", descrizione:"Aumenta l'Evasività dell'utente di 2 stadi." },
  109: { nome:"Doppio Schiaffo", tipo:"normal", cat:"fisico", potenza:15, accuratezza:85, pp:10, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  110: { nome:"Ira", tipo:"normal", cat:"fisico", potenza:20, accuratezza:100, pp:20, effetto:null, descrizione:"L'utente non può far nulla per 2-3 turni dopo l'uso." },
  111: { nome:"Frustata", tipo:"normal", cat:"fisico", potenza:60, accuratezza:100, pp:25, effetto:null, descrizione:"Nessun effetto secondario." },
  112: { nome:"Coda Ferreo", tipo:"steel", cat:"fisico", potenza:100, accuratezza:75, pp:5, effetto:"abbassa_dif_1", descrizione:"30% di probabilità di abbassare la Difesa del bersaglio." },
  113: { nome:"Pugnopugno", tipo:"fighting", cat:"fisico", potenza:150, accuratezza:100, pp:5, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale dell'utente di 2 stadi." },
  114: { nome:"Schiaccianoci", tipo:"fighting", cat:"fisico", potenza:120, accuratezza:100, pp:15, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale dell'utente di 1 stadio." },
  115: { nome:"Karatcolpo", tipo:"fighting", cat:"fisico", potenza:50, accuratezza:100, pp:25, effetto:null, descrizione:"Nessun effetto secondario." },
  116: { nome:"Contrattacco", tipo:"fighting", cat:"fisico", potenza:0, accuratezza:100, pp:20, effetto:null, descrizione:"Restituisce il doppio del danno subito dall'ultimo attacco fisico." },
  117: { nome:"Colpobasso", tipo:"fighting", cat:"fisico", potenza:40, accuratezza:100, pp:35, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  118: { nome:"Lottasfrenata", tipo:"fighting", cat:"fisico", potenza:120, accuratezza:100, pp:15, effetto:null, descrizione:"Abbassa tutte le statistiche dell'utente di 1 stadio." },
  119: { nome:"Osseoclub", tipo:"ground", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_dif_1", descrizione:"Può abbassare la Difesa del bersaglio." },
  120: { nome:"Osseofreccia", tipo:"ground", cat:"fisico", potenza:25, accuratezza:90, pp:10, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  121: { nome:"Fantasmattacco", tipo:"ghost", cat:"fisico", potenza:20, accuratezza:100, pp:10, effetto:null, descrizione:"Il bersaglio non può fuggire o essere cambiato." },
  122: { nome:"Bacio Gelido", tipo:"ice", cat:"fisico", potenza:35, accuratezza:85, pp:25, effetto:"congelamento_100", descrizione:"100% di probabilità di congelare il bersaglio." },
  123: { nome:"Vortice di Ghiaccio", tipo:"ice", cat:"speciale", potenza:50, accuratezza:70, pp:15, effetto:"intrappola", descrizione:"Intrappola il bersaglio per 4-5 turni." },
  124: { nome:"Raggio Aurora", tipo:"ice", cat:"speciale", potenza:65, accuratezza:100, pp:20, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  125: { nome:"Blizzard", tipo:"ice", cat:"speciale", potenza:110, accuratezza:70, pp:5, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare tutti i bersagli." },
  126: { nome:"Rompiroccia", tipo:"rock", cat:"fisico", potenza:40, accuratezza:100, pp:15, effetto:"abbassa_dif_1", descrizione:"Può abbassare la Difesa del bersaglio." },
  127: { nome:"Pietrata", tipo:"rock", cat:"fisico", potenza:50, accuratezza:90, pp:15, effetto:"abbassa_spd_1", descrizione:"Può abbassare la Difesa Speciale del bersaglio." },
  128: { nome:"Turbosabbia", tipo:"rock", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:null, descrizione:"Infligge danni da Tempesta di Sabbia per 5 turni." },
  129: { nome:"Difendiamoci", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Azzera il danno di un attacco fisico questo turno." },
  130: { nome:"Schivata", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Azzera il danno di un attacco fisico questo turno." },
  131: { nome:"Mimetismo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Cambia il tipo dell'utente in base al terreno." },
  132: { nome:"Mossa Specchio", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Copia l'ultima mossa usata dal bersaglio." },
  133: { nome:"Schizzo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:1, effetto:null, descrizione:"Copia permanentemente la mossa dell'avversario." },
  134: { nome:"Falso Graffio", tipo:"normal", cat:"fisico", potenza:40, accuratezza:100, pp:40, effetto:null, descrizione:"Lascia sempre 1 PV al bersaglio." },
  135: { nome:"Colpo Basso (Fighting)", tipo:"fighting", cat:"fisico", potenza:40, accuratezza:100, pp:30, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  136: { nome:"Colpo Segreto", tipo:"normal", cat:"fisico", potenza:70, accuratezza:100, pp:20, effetto:null, descrizione:"Colpisce per primo i Pokémon in procinto di cambiare." },
  137: { nome:"Soffio Vitale", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Trasferisce i propri problemi di stato all'avversario." },
  138: { nome:"Mossa Spettacolo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Costringe il bersaglio a usare la stessa mossa per 3 turni." },
  139: { nome:"Copia", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Crea un sosia dell'utente che assorbe i danni." },
  140: { nome:"Autodistruzione", tipo:"normal", cat:"fisico", potenza:200, accuratezza:100, pp:5, effetto:"esplosione", descrizione:"L'utente sviene. Infligge enorme danno." },
  141: { nome:"Esplosione", tipo:"normal", cat:"fisico", potenza:250, accuratezza:100, pp:5, effetto:"esplosione", descrizione:"L'utente sviene. Infligge danno devastante." },
  142: { nome:"Riassorbimento", tipo:"normal", cat:"speciale", potenza:0, accuratezza:100, pp:10, effetto:null, descrizione:"Assorbe 1/4 PV del bersaglio per 4-5 turni." },
  143: { nome:"Muro di Luce", tipo:"psychic", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Dimezza il danno degli attacchi speciali per 5 turni." },
  144: { nome:"Specchio Magico", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:null, descrizione:"Riflette le mosse di stato dei nemici." },
  145: { nome:"Nebbia", tipo:"ice", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Previene l'abbassamento delle statistiche per 5 turni." },
  146: { nome:"Acquascudo", tipo:"water", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Dimezza i danni fisici subiti per 5 turni." },
  147: { nome:"Fossa Comune", tipo:"ground", cat:"fisico", potenza:80, accuratezza:100, pp:10, effetto:"intrappola", descrizione:"Se il bersaglio è a terra, lo intrappola." },
  148: { nome:"Ombra Notturna", tipo:"dark", cat:"speciale", potenza:0, accuratezza:100, pp:15, effetto:"danno_fisso_livello", descrizione:"Infligge danni pari al livello dell'utente." },
  149: { nome:"Potere Nascosto", tipo:"normal", cat:"speciale", potenza:60, accuratezza:100, pp:15, effetto:null, descrizione:"Il tipo varia in base alle statistiche individuali." },
  150: { nome:"Folgore Solare", tipo:"grass", cat:"speciale", potenza:120, accuratezza:100, pp:10, effetto:"due_turni_carica", descrizione:"Il turno 1 si carica; il turno 2 colpisce." },
  151: { nome:"Raggio Solare", tipo:"grass", cat:"speciale", potenza:120, accuratezza:100, pp:10, effetto:"due_turni_carica", descrizione:"Si carica al turno 1 e colpisce al turno 2." },
  152: { nome:"Megacalcio", tipo:"fighting", cat:"fisico", potenza:120, accuratezza:75, pp:5, effetto:null, descrizione:"Causa danni ad un Pokémon grande. Danno raddoppiato." },
  153: { nome:"Colpo Fulmine", tipo:"normal", cat:"fisico", potenza:100, accuratezza:100, pp:15, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  154: { nome:"Testacoda", tipo:"normal", cat:"fisico", potenza:150, accuratezza:90, pp:5, effetto:null, descrizione:"L'utente subisce il 25% del danno inflitto." },
  155: { nome:"Capovolta", tipo:"normal", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:null, descrizione:"Più è alto il livello del user, più danno fa." },
  156: { nome:"Soffiomalefico", tipo:"ghost", cat:"speciale", potenza:80, accuratezza:100, pp:15, effetto:null, descrizione:"Il bersaglio non può fuggire." },
  157: { nome:"Giro Rapido", tipo:"normal", cat:"fisico", potenza:50, accuratezza:100, pp:40, effetto:null, descrizione:"Rimuove trappole, spine ed effetti di stallo." },
  158: { nome:"Saldatura", tipo:"steel", cat:"fisico", potenza:50, accuratezza:90, pp:25, effetto:"colpo_critico_alto", descrizione:"Ha sempre la stessa probabilità di colpo critico." },
  159: { nome:"Fascino", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:20, effetto:"abbassa_atk_2", descrizione:"Abbassa l'Attacco del bersaglio di 2 stadi se di sesso opposto." },
  160: { nome:"Ammaliamento", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:null, descrizione:"Abbassa varie statistiche del bersaglio di sesso opposto." },
  161: { nome:"Canto", tipo:"normal", cat:"stato", potenza:0, accuratezza:55, pp:15, effetto:"sonno", descrizione:"Addormenta il bersaglio." },
  162: { nome:"Occhio Luce", tipo:"psychic", cat:"speciale", potenza:40, accuratezza:100, pp:30, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale del bersaglio di 1 stadio." },
  163: { nome:"Sferza", tipo:"dark", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:"confusione_50", descrizione:"Infligge il 50% dei danni in più se il bersaglio è in stato di confusione." },
  164: { nome:"Nemesi", tipo:"dark", cat:"fisico", potenza:0, accuratezza:100, pp:10, effetto:null, descrizione:"Infligge danni tanto maggiori quanto più il user ha perso PV." },
  165: { nome:"Notte Stellata", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"cura_meta", descrizione:"Recupera metà dei PV massimi di notte." },
  166: { nome:"Rapina", tipo:"dark", cat:"fisico", potenza:60, accuratezza:100, pp:25, effetto:null, descrizione:"Se il bersaglio porta un oggetto, lo ruba." },
  167: { nome:"Scoppio", tipo:"dark", cat:"fisico", potenza:120, accuratezza:100, pp:10, effetto:"confusione_10", descrizione:"Causa sempre danni critici se il user è in stato di confusione." },
  168: { nome:"Tormento", tipo:"dark", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:null, descrizione:"Il bersaglio non può usare la stessa mossa due volte di fila." },
  169: { nome:"Rabbuiarsi", tipo:"dark", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:"abbassa_acc_1", descrizione:"Abbassa l'Accuratezza del bersaglio di 1 stadio." },
  170: { nome:"Psicotaglio", tipo:"psychic", cat:"fisico", potenza:70, accuratezza:100, pp:20, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  171: { nome:"Raggio Notte", tipo:"dark", cat:"speciale", potenza:80, accuratezza:100, pp:15, effetto:null, descrizione:"Il bersaglio non può fuggire o essere cambiato per 1-5 turni." },
  172: { nome:"Soffio di Drago", tipo:"dragon", cat:"speciale", potenza:60, accuratezza:100, pp:20, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  173: { nome:"Ira del Drago", tipo:"dragon", cat:"speciale", potenza:0, accuratezza:100, pp:10, effetto:"danno_fisso_livello", descrizione:"Infligge 40 danni fissi sempre." },
  174: { nome:"Coda di Drago", tipo:"dragon", cat:"fisico", potenza:60, accuratezza:90, pp:10, effetto:null, descrizione:"Forza il cambio del Pokémon avversario." },
  175: { nome:"Danza del Drago", tipo:"dragon", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_1", descrizione:"Aumenta l'Attacco e la Velocità dell'utente di 1 stadio." },
  176: { nome:"Polpo al Volto", tipo:"normal", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"confusione_10", descrizione:"Può confondere il bersaglio." },
  177: { nome:"Colpo di Coda", tipo:"normal", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  178: { nome:"Tempesta di Fuoco", tipo:"fire", cat:"speciale", potenza:150, accuratezza:90, pp:5, effetto:"ustione_10", descrizione:"Può ustionare il bersaglio." },
  179: { nome:"Azione di Fuoco", tipo:"fire", cat:"speciale", potenza:60, accuratezza:100, pp:25, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  180: { nome:"Sferzavento", tipo:"flying", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  181: { nome:"Aquila", tipo:"flying", cat:"fisico", potenza:65, accuratezza:100, pp:15, effetto:"abbassa_dif_1", descrizione:"Può abbassare la Difesa del bersaglio." },
  182: { nome:"Nitido", tipo:"psychic", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:"alza_spa_1", descrizione:"Aumenta l'Attacco Speciale e la Difesa Speciale dell'utente di 1 stadio." },
  183: { nome:"Gocciolone", tipo:"water", cat:"speciale", potenza:60, accuratezza:100, pp:20, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  184: { nome:"Idrocannone", tipo:"water", cat:"speciale", potenza:150, accuratezza:90, pp:5, effetto:"ricarica", descrizione:"L'utente deve ricaricare al turno successivo." },
  185: { nome:"Zampata Fango", tipo:"ground", cat:"speciale", potenza:20, accuratezza:100, pp:10, effetto:"abbassa_vel_1", descrizione:"100% di probabilità di abbassare la Velocità del bersaglio." },
  186: { nome:"Bomba Melma", tipo:"poison", cat:"speciale", potenza:65, accuratezza:100, pp:20, effetto:"veleno_30", descrizione:"30% di probabilità di avvelenare il bersaglio." },
  187: { nome:"Pantano", tipo:"ground", cat:"speciale", potenza:55, accuratezza:95, pp:10, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità del bersaglio di 1 stadio." },
  188: { nome:"Fangobomba", tipo:"ground", cat:"speciale", potenza:90, accuratezza:85, pp:10, effetto:"abbassa_spd_1", descrizione:"30% di probabilità di abbassare la Difesa Speciale del bersaglio." },
  189: { nome:"Splatter", tipo:"water", cat:"speciale", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_acc_1", descrizione:"Abbassa l'Accuratezza del bersaglio di 1 stadio." },
  190: { nome:"Terrapesta", tipo:"ground", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità del bersaglio di 1 stadio." },
  191: { nome:"Segnale", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"alza_vel_2", descrizione:"Aumenta la Velocità dell'utente di 2 stadi." },
  192: { nome:"Sciame", tipo:"bug", cat:"fisico", potenza:75, accuratezza:85, pp:10, effetto:null, descrizione:"Aumenta la potenza quando i PV sono bassi." },
  193: { nome:"Zuffa", tipo:"bug", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:"abbassa_spd_1", descrizione:"30% di probabilità di abbassare la Difesa Speciale del bersaglio." },
  194: { nome:"Ronzio", tipo:"bug", cat:"stato", potenza:0, accuratezza:100, pp:20, effetto:"abbassa_spa_1", descrizione:"Abbassa l'Attacco Speciale del bersaglio di 1 stadio." },
  195: { nome:"Aculeo", tipo:"bug", cat:"fisico", potenza:35, accuratezza:95, pp:30, effetto:"veleno_30", descrizione:"30% di probabilità di avvelenare il bersaglio." },
  196: { nome:"Osseo", tipo:"ground", cat:"fisico", potenza:65, accuratezza:90, pp:20, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  197: { nome:"Ombre Notturne", tipo:"ghost", cat:"fisico", potenza:30, accuratezza:100, pp:15, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio di 1 stadio." },
  198: { nome:"Forza Spettro", tipo:"ghost", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"paralisi_30", descrizione:"Può paralizzare il bersaglio." },
  199: { nome:"Tenebre", tipo:"dark", cat:"fisico", potenza:50, accuratezza:100, pp:15, effetto:null, descrizione:"Abbassa le statistiche del bersaglio di 1 stadio casuale." },
  200: { nome:"Brutto Muso", tipo:"dark", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:"abbassa_atk_1", descrizione:"Abbassa l'Attacco del bersaglio di 1 stadio." },
  201: { nome:"Ghigno", tipo:"dark", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:"abbassa_dif_2", descrizione:"Abbassa la Difesa del bersaglio di 2 stadi." },
  202: { nome:"Riflesso", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Dimezza i danni fisici subiti per 5 turni (schermo)." },
  203: { nome:"Finta", tipo:"normal", cat:"fisico", potenza:30, accuratezza:100, pp:10, effetto:"critico_sempre", descrizione:"Sempre colpo critico." },
  204: { nome:"Allarme", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Raddoppia la velocità dei Pokémon in campo." },
  205: { nome:"Ritorno", tipo:"normal", cat:"fisico", potenza:0, accuratezza:100, pp:20, effetto:null, descrizione:"Più il Pokémon è amichevole, più forte è la mossa (max 102)." },
  206: { nome:"Frustrazione", tipo:"normal", cat:"fisico", potenza:0, accuratezza:100, pp:20, effetto:null, descrizione:"Più il Pokémon è infelice, più forte è la mossa (max 102)." },
  207: { nome:"Forza Nascosta", tipo:"normal", cat:"fisico", potenza:70, accuratezza:100, pp:20, effetto:null, descrizione:"Può alzare tutte le statistiche dell'utente." },
  208: { nome:"Dono", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Trasferisce l'oggetto tenuto al compagno di squadra." },
  209: { nome:"Demolizione", tipo:"normal", cat:"fisico", potenza:90, accuratezza:85, pp:5, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale dell'utente di 1 stadio." },
  210: { nome:"Mossa Falsa", tipo:"normal", cat:"fisico", potenza:40, accuratezza:100, pp:40, effetto:null, descrizione:"Lascia il bersaglio con 1 PV." },
  211: { nome:"Doppio Sbuffo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale del bersaglio di 2 stadi." },
  212: { nome:"Polvere Magica", tipo:"grass", cat:"stato", potenza:0, accuratezza:75, pp:15, effetto:"paralisi_100", descrizione:"Paralizza il bersaglio." },
  213: { nome:"Pietrificazione", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Dimezza i danni speciali subiti per 5 turni." },
  214: { nome:"Insidia", tipo:"dark", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Riduce i PV del bersaglio alla metà di quelli dell'utente." },
  215: { nome:"Spettrosfida", tipo:"ghost", cat:"stato", potenza:0, accuratezza:100, pp:10, effetto:null, descrizione:"Riduce i PV del bersaglio alla metà dei propri." },
  216: { nome:"Stordimento", tipo:"normal", cat:"fisico", potenza:30, accuratezza:100, pp:15, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio (30% paralisi)." },
  217: { nome:"Anello di Fuoco", tipo:"fire", cat:"fisico", potenza:35, accuratezza:85, pp:15, effetto:"ustione_100", descrizione:"Intrappola e ustiona il bersaglio per 4-5 turni." },
  218: { nome:"Lanciafiamme Sacro", tipo:"fire", cat:"speciale", potenza:100, accuratezza:95, pp:5, effetto:null, descrizione:"Colpisce sempre se il bersaglio usa Solare." },
  219: { nome:"Combustione", tipo:"fire", cat:"speciale", potenza:80, accuratezza:100, pp:15, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  220: { nome:"Onda Ignea", tipo:"fire", cat:"speciale", potenza:95, accuratezza:90, pp:5, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  221: { nome:"Bora", tipo:"ice", cat:"speciale", potenza:55, accuratezza:95, pp:15, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  222: { nome:"Pungolo di Ghiaccio", tipo:"ice", cat:"fisico", potenza:75, accuratezza:95, pp:15, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  223: { nome:"Tempesta di Neve", tipo:"ice", cat:"speciale", potenza:55, accuratezza:100, pp:15, effetto:null, descrizione:"Colpisce entrambi i nemici in doppia battaglia." },
  224: { nome:"Grandinata", tipo:"ice", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Attiva la grandine per 5 turni. Potenzia mosse ghiaccio." },
  225: { nome:"Colpo di Tuono", tipo:"electric", cat:"fisico", potenza:65, accuratezza:100, pp:15, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  226: { nome:"Rete Elettrica", tipo:"electric", cat:"speciale", potenza:55, accuratezza:95, pp:15, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  227: { nome:"Rullo Ferro", tipo:"steel", cat:"fisico", potenza:30, accuratezza:90, pp:20, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  228: { nome:"Zanna Acciaio", tipo:"steel", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"abbassa_dif_1", descrizione:"10% di probabilità di abbassare la Difesa del bersaglio." },
  229: { nome:"Scoppio Argenteo", tipo:"steel", cat:"speciale", potenza:50, accuratezza:100, pp:40, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale del bersaglio di 1 stadio." },
  230: { nome:"Berserk", tipo:"normal", cat:"fisico", potenza:20, accuratezza:100, pp:20, effetto:null, descrizione:"La potenza aumenta di 20 ad ogni turno (max 200)." },
  231: { nome:"Lancio di Fango", tipo:"ground", cat:"speciale", potenza:20, accuratezza:100, pp:10, effetto:"abbassa_acc_1", descrizione:"100% di probabilità di abbassare l'Accuratezza del bersaglio." },
  232: { nome:"Osseo Boomerang", tipo:"ground", cat:"fisico", potenza:25, accuratezza:90, pp:10, effetto:"colpisce_due", descrizione:"Colpisce due volte per turno." },
  233: { nome:"Metronomo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Usa una mossa a caso tra tutte quelle esistenti." },
  234: { nome:"Copi", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Copia la mossa del bersaglio. Solo 5 PP." },
  235: { nome:"Attrazione", tipo:"normal", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:null, descrizione:"Innamora il bersaglio di sesso opposto. 50% non attacca." },
  236: { nome:"Sfida", tipo:"fighting", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Obbliga il bersaglio a attaccare solo l'utente." },
  237: { nome:"Abilità Nascosta", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"alza_spd_1", descrizione:"Aumenta Attacco o Difesa Speciale di 1 stadio." },
  238: { nome:"Triplattacco", tipo:"normal", cat:"fisico", potenza:80, accuratezza:100, pp:10, effetto:"paralisi_30", descrizione:"Può bruciare, congelare o paralizzare il bersaglio." },
  239: { nome:"Urlo di Guerra", tipo:"fighting", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_1", descrizione:"Aumenta l'Attacco di tutti i compagni di squadra di 1 stadio." },
  240: { nome:"Colpo Fulmineo", tipo:"electric", cat:"fisico", potenza:50, accuratezza:95, pp:10, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  241: { nome:"Roccia Affilata", tipo:"rock", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Piazza mine di roccia che danneggiano i Pokémon in entrata." },
  242: { nome:"Spiritospina", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Infligge danni a chi usa mosse di contatto contro l'utente." },
  243: { nome:"Dispettuccio", tipo:"dark", cat:"stato", potenza:0, accuratezza:100, pp:10, effetto:null, descrizione:"Dimezza i PP della mossa del bersaglio." },
  244: { nome:"Fiele", tipo:"poison", cat:"stato", potenza:0, accuratezza:85, pp:40, effetto:"veleno_tossico", descrizione:"Avvelena gravemente il bersaglio (veleno tossico)." },
  245: { nome:"Mossacadente", tipo:"normal", cat:"fisico", potenza:20, accuratezza:100, pp:5, effetto:null, descrizione:"L'utente utilizza le mosse del bersaglio contro di lui." },
  246: { nome:"Inchino", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:40, effetto:"alza_eva_1", descrizione:"Aumenta l'Evasività dell'utente di 1 stadio." },
  247: { nome:"Buonanotte", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"sonno", descrizione:"Addormenta tutti i Pokémon in campo." },
  248: { nome:"Sostituto", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Crea un sosia con 1/4 dei PV per assorbire gli attacchi." },
  249: { nome:"Soffio d'Aria", tipo:"normal", cat:"speciale", potenza:29, accuratezza:95, pp:25, effetto:null, descrizione:"Sempre efficace contro i Pokémon che volano." },
  250: { nome:"Tutela", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Protegge da qualsiasi attacco questo turno." },
  251: { nome:"Rocciata", tipo:"rock", cat:"fisico", potenza:25, accuratezza:90, pp:15, effetto:"abbassa_spd_1", descrizione:"Può abbassare la Difesa Speciale del bersaglio." },
  252: { nome:"Danza Pioggia", tipo:"water", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Attiva la pioggia per 5 turni. Potenzia mosse acqua." },
  253: { nome:"Abbraccio", tipo:"normal", cat:"fisico", potenza:70, accuratezza:90, pp:20, effetto:"paralisi_30", descrizione:"Può paralizzare il bersaglio." },
  254: { nome:"Blocco Luce", tipo:"psychic", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Dimezza i danni speciali subiti per 5 turni." },
  255: { nome:"Psicoblast", tipo:"psychic", cat:"speciale", potenza:80, accuratezza:100, pp:10, effetto:"danno_fisso_livello", descrizione:"Infligge danni fissi pari al livello dell'utente." },
  256: { nome:"Zanna Tuono", tipo:"electric", cat:"fisico", potenza:65, accuratezza:95, pp:15, effetto:"paralisi_30", descrizione:"30% di probabilità di paralizzare il bersaglio." },
  257: { nome:"Zanna Fuoco", tipo:"fire", cat:"fisico", potenza:65, accuratezza:95, pp:15, effetto:"ustione_10", descrizione:"10% di probabilità di ustionare il bersaglio." },
  258: { nome:"Zanna Ghiaccio", tipo:"ice", cat:"fisico", potenza:65, accuratezza:95, pp:15, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  259: { nome:"Danzanuda", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_vel_2", descrizione:"Aumenta la Velocità dell'utente di 2 stadi. Abbassa la Difesa di 1." },
  260: { nome:"Controspinta", tipo:"fighting", cat:"fisico", potenza:0, accuratezza:100, pp:10, effetto:null, descrizione:"Infligge il doppio del danno fisico subito." },
  261: { nome:"Rabbia", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"abbassa_atk_1", descrizione:"Abbassa l'Attacco del bersaglio di 1 stadio." },
  262: { nome:"Assurdo", tipo:"psychic", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:null, descrizione:"Ignora le modifiche alle statistiche del bersaglio." },
  263: { nome:"Rispecchio", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Riflette le mosse speciali del bersaglio per 5 turni." },
  264: { nome:"Azione Sonica", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Impedisce al bersaglio di fuggire per 4-5 turni." },
  265: { nome:"Schianta", tipo:"fighting", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  266: { nome:"Tempesta Solare", tipo:"fire", cat:"speciale", potenza:150, accuratezza:90, pp:5, effetto:"ustione_100", descrizione:"Il turno 1 carica; il turno 2 colpisce. Ustiona." },
  267: { nome:"Calamitosum", tipo:"psychic", cat:"speciale", potenza:100, accuratezza:100, pp:10, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale del bersaglio di 2 stadi." },
  268: { nome:"Allarme Bomba", tipo:"steel", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio di 1 stadio." },
  269: { nome:"Spaccatura", tipo:"normal", cat:"fisico", potenza:80, accuratezza:75, pp:20, effetto:null, descrizione:"Colpisce bersagli che usano Tuffo o Scavata." },
  270: { nome:"Acqua Anello", tipo:"water", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Recupera 1/16 PV per turno per 5 turni." },
  271: { nome:"Acquabomba", tipo:"water", cat:"speciale", potenza:80, accuratezza:100, pp:10, effetto:"confusione_20", descrizione:"20% di probabilità di confondere il bersaglio." },
  272: { nome:"Energibomba", tipo:"grass", cat:"speciale", potenza:80, accuratezza:100, pp:10, effetto:"abbassa_spd_1", descrizione:"10% di probabilità di abbassare la Difesa Speciale." },
  273: { nome:"Sigillo di Fuoco", tipo:"fire", cat:"speciale", potenza:80, accuratezza:100, pp:10, effetto:"ustione_20", descrizione:"20% di probabilità di ustionare il bersaglio." },
  274: { nome:"Razzo Foglia", tipo:"grass", cat:"fisico", potenza:90, accuratezza:100, pp:15, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  275: { nome:"Raggio Ghiaccio", tipo:"ice", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:"congelamento_10", descrizione:"10% di probabilità di congelare il bersaglio." },
  276: { nome:"Onda Tonante", tipo:"electric", cat:"speciale", potenza:60, accuratezza:100, pp:20, effetto:"paralisi_20", descrizione:"20% di probabilità di paralizzare il bersaglio." },
  277: { nome:"Lama Sferzante", tipo:"steel", cat:"fisico", potenza:70, accuratezza:100, pp:25, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  278: { nome:"Coltellata", tipo:"dark", cat:"fisico", potenza:70, accuratezza:100, pp:25, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  279: { nome:"Soffio Vitale (Drago)", tipo:"dragon", cat:"speciale", potenza:80, accuratezza:100, pp:10, effetto:"ustione_100", descrizione:"Può paralizzare, ustionare o congelare il bersaglio." },
  280: { nome:"Meteora Draconica", tipo:"dragon", cat:"speciale", potenza:140, accuratezza:90, pp:5, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale dell'utente di 2 stadi." },
  281: { nome:"Danza Drago", tipo:"dragon", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_1", descrizione:"Aumenta Attacco e Velocità dell'utente di 1 stadio." },
  282: { nome:"Folgore Draconica", tipo:"dragon", cat:"fisico", potenza:120, accuratezza:100, pp:10, effetto:"esplosione", descrizione:"L'utente sviene dopo l'uso." },
  283: { nome:"Giro Veloce", tipo:"normal", cat:"fisico", potenza:20, accuratezza:100, pp:40, effetto:"alza_vel_1", descrizione:"Aumenta la Velocità dell'utente di 1 stadio." },
  284: { nome:"Tutela Plus", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Protegge dagli attacchi e può far perdere la concentrazione." },
  285: { nome:"Ombra Fantasma", tipo:"ghost", cat:"speciale", potenza:80, accuratezza:100, pp:15, effetto:"abbassa_spd_1", descrizione:"20% di probabilità di abbassare la Difesa Speciale." },
  286: { nome:"Martello Ombra", tipo:"ghost", cat:"fisico", potenza:40, accuratezza:100, pp:15, effetto:"critico_sempre", descrizione:"Sempre colpo critico." },
  287: { nome:"Tentacolo Ombra", tipo:"ghost", cat:"fisico", potenza:65, accuratezza:100, pp:10, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  288: { nome:"Maleodore", tipo:"poison", cat:"stato", potenza:0, accuratezza:90, pp:10, effetto:"veleno_tossico", descrizione:"Avvelena gravemente il bersaglio." },
  289: { nome:"Tossina", tipo:"poison", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"veleno_tossico", descrizione:"Avvelena gravemente il bersaglio all'istante." },
  290: { nome:"Punta Velenosa", tipo:"poison", cat:"fisico", potenza:50, accuratezza:100, pp:20, effetto:"veleno_30", descrizione:"30% di probabilità di avvelenare il bersaglio." },
  291: { nome:"Zanna Avvelena", tipo:"poison", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"veleno_100", descrizione:"100% di probabilità di avvelenare il bersaglio." },
  292: { nome:"Ricarica", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"cura_meta", descrizione:"L'utente recupera metà dei PV persi nel turno precedente." },
  293: { nome:"Assimila", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Assorbe PV pari a 1/4 dei PV massimi del bersaglio." },
  294: { nome:"Affilatura", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"alza_atk_1", descrizione:"Aumenta l'Attacco dell'utente di 1 stadio." },
  295: { nome:"Ululato Gelido", tipo:"ice", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità dei nemici di 1 stadio." },
  296: { nome:"Boato", tipo:"normal", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:"paralisi_10", descrizione:"10% di probabilità di far tremare il bersaglio." },
  297: { nome:"Rimbombo", tipo:"rock", cat:"speciale", potenza:150, accuratezza:90, pp:5, effetto:"due_turni_carica", descrizione:"Il turno 1 si carica, il turno 2 colpisce." },
  298: { nome:"Meteoora", tipo:"rock", cat:"fisico", potenza:120, accuratezza:100, pp:5, effetto:null, descrizione:"Non può essere usata al primo turno." },
  299: { nome:"Erosione", tipo:"rock", cat:"fisico", potenza:40, accuratezza:100, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio di 1 stadio." },
  300: { nome:"Terremoto Acuta", tipo:"ground", cat:"fisico", potenza:65, accuratezza:100, pp:20, effetto:null, descrizione:"Colpisce anche i Pokémon che usano Scavata." },
  301: { nome:"Lancio Sabbia", tipo:"ground", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:"alza_eva_1", descrizione:"Aumenta l'Evasività in tempesta di sabbia." },
  302: { nome:"Acquazzone", tipo:"water", cat:"speciale", potenza:50, accuratezza:100, pp:30, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  303: { nome:"Sferzata d'Acqua", tipo:"water", cat:"fisico", potenza:80, accuratezza:100, pp:10, effetto:"confusione_10", descrizione:"Può confondere il bersaglio." },
  304: { nome:"Guscio di Ferro", tipo:"steel", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:"alza_dif_2", descrizione:"Aumenta la Difesa dell'utente di 2 stadi." },
  305: { nome:"Testa di Ferro", tipo:"steel", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:"paralisi_30", descrizione:"30% di probabilità di far tremare il bersaglio." },
  306: { nome:"Cannone d'Argento", tipo:"steel", cat:"speciale", potenza:100, accuratezza:100, pp:5, effetto:"abbassa_spa_2", descrizione:"Abbassa l'Attacco Speciale dell'utente di 2 stadi." },
  307: { nome:"Iper Raggio", tipo:"normal", cat:"speciale", potenza:150, accuratezza:90, pp:5, effetto:"ricarica", descrizione:"L'utente deve ricaricare al turno successivo." },
  308: { nome:"Giganteforza", tipo:"normal", cat:"fisico", potenza:150, accuratezza:90, pp:5, effetto:"ricarica", descrizione:"L'utente deve ricaricare al turno successivo." },
  309: { nome:"Artiglio Ombra", tipo:"dark", cat:"fisico", potenza:50, accuratezza:100, pp:20, effetto:"abbassa_eva_1", descrizione:"Abbassa l'Evasività del bersaglio di 1 stadio." },
  310: { nome:"Mossa Z", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:1, effetto:null, descrizione:"Usata solo in condizioni speciali." },
  311: { nome:"Onda Psichica", tipo:"psychic", cat:"speciale", potenza:65, accuratezza:100, pp:20, effetto:"confusione_10", descrizione:"10% di probabilità di confondere il bersaglio." },
  312: { nome:"Psicoforza", tipo:"psychic", cat:"fisico", potenza:90, accuratezza:100, pp:10, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale del bersaglio di 1 stadio." },
  313: { nome:"Vuoto", tipo:"psychic", cat:"speciale", potenza:0, accuratezza:0, pp:5, effetto:"sonno", descrizione:"Addormenta tutti i Pokémon in campo." },
  314: { nome:"Aiutoaiuto", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:null, descrizione:"Chiama aiuto in battaglia a doppio." },
  315: { nome:"Lancio di Pietre", tipo:"rock", cat:"fisico", potenza:50, accuratezza:90, pp:15, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  316: { nome:"Gira Gira", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:15, effetto:null, descrizione:"L'utente scambia la sua Difesa e il suo Attacco Speciale." },
  317: { nome:"Piroball", tipo:"fire", cat:"fisico", potenza:15, accuratezza:85, pp:20, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  318: { nome:"Sorpresa", tipo:"normal", cat:"fisico", potenza:40, accuratezza:100, pp:30, effetto:"priorita_p1", descrizione:"Va sempre per primo (priorità +1)." },
  319: { nome:"Maschera Oscura", tipo:"dark", cat:"stato", potenza:0, accuratezza:100, pp:15, effetto:"abbassa_atk_1", descrizione:"Abbassa l'Attacco del bersaglio di 1 stadio." },
  320: { nome:"Mossaspettacolo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:null, descrizione:"Scambia le mosse con il bersaglio permanentemente." },
  321: { nome:"Corrosione Acida", tipo:"poison", cat:"speciale", potenza:50, accuratezza:100, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio." },
  322: { nome:"Graffio d'Acido", tipo:"poison", cat:"fisico", potenza:40, accuratezza:100, pp:30, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa del bersaglio." },
  323: { nome:"Esplosione Acida", tipo:"poison", cat:"speciale", potenza:90, accuratezza:100, pp:10, effetto:"veleno_tossico", descrizione:"Può avvelenare gravemente il bersaglio." },
  324: { nome:"Brace Solare", tipo:"grass", cat:"fisico", potenza:75, accuratezza:100, pp:10, effetto:"due_turni_carica", descrizione:"Richiede carica al sole; altrimenti solo 37,5 di danno." },
  325: { nome:"Granata Seme", tipo:"grass", cat:"fisico", potenza:80, accuratezza:100, pp:15, effetto:null, descrizione:"Semina il bersaglio: drena PV ogni turno." },
  326: { nome:"Foglia Lama", tipo:"grass", cat:"fisico", potenza:90, accuratezza:100, pp:15, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
  327: { nome:"Petali Danza", tipo:"grass", cat:"speciale", potenza:120, accuratezza:100, pp:10, effetto:"confusione_10", descrizione:"L'utente si confonde dopo 2-3 turni." },
  328: { nome:"Vortice Foglie", tipo:"grass", cat:"speciale", potenza:40, accuratezza:100, pp:20, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  329: { nome:"Magia Foglia", tipo:"grass", cat:"speciale", potenza:60, accuratezza:100, pp:20, effetto:"colpo_critico_alto", descrizione:"Infligge sempre un colpo critico." },
  330: { nome:"Semi Velenosi", tipo:"poison", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:"veleno_100", descrizione:"Avvelena il bersaglio." },
  331: { nome:"Seme Pianto", tipo:"grass", cat:"stato", potenza:0, accuratezza:90, pp:10, effetto:null, descrizione:"Drena PV dal bersaglio ogni turno." },
  332: { nome:"Sintesi", tipo:"grass", cat:"stato", potenza:0, accuratezza:0, pp:5, effetto:"cura_meta", descrizione:"Recupera PV. L'effetto varia col meteo." },
  333: { nome:"Erbacce", tipo:"grass", cat:"fisico", potenza:55, accuratezza:95, pp:25, effetto:"abbassa_vel_1", descrizione:"Può abbassare la Velocità del bersaglio." },
  334: { nome:"Riflettori", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:"abbassa_atk_1", descrizione:"Abbassa Attacco e Difesa Speciale del bersaglio." },
  335: { nome:"Richiamo", tipo:"normal", cat:"stato", potenza:0, accuratezza:0, pp:30, effetto:null, descrizione:"Forza il cambio del Pokémon avversario." },
  336: { nome:"Raggio Segnale", tipo:"normal", cat:"speciale", potenza:0, accuratezza:100, pp:15, effetto:"abbassa_acc_1", descrizione:"Abbassa l'Accuratezza del bersaglio di 1 stadio." },
  337: { nome:"Lancio di Sale", tipo:"ground", cat:"fisico", potenza:40, accuratezza:100, pp:15, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità del bersaglio." },
  338: { nome:"Tuono Ritmico", tipo:"electric", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"abbassa_spd_2", descrizione:"Abbassa la Difesa Speciale del bersaglio di 2 stadi." },
  339: { nome:"Scossa Elettrica", tipo:"electric", cat:"speciale", potenza:40, accuratezza:100, pp:30, effetto:"paralisi_10", descrizione:"10% di probabilità di paralizzare il bersaglio." },
  340: { nome:"Commozione", tipo:"normal", cat:"fisico", potenza:30, accuratezza:85, pp:10, effetto:"paralisi_30", descrizione:"Può far tremare il bersaglio." },
  341: { nome:"Nebbia Acida", tipo:"poison", cat:"speciale", potenza:40, accuratezza:100, pp:20, effetto:"abbassa_spd_1", descrizione:"Abbassa la Difesa Speciale del bersaglio." },
  342: { nome:"Danza Petali", tipo:"grass", cat:"speciale", potenza:120, accuratezza:100, pp:10, effetto:"confusione_10", descrizione:"L'utente si confonde dopo 2-3 turni." },
  343: { nome:"Grido di Battaglia", tipo:"fighting", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"abbassa_dif_1", descrizione:"Abbassa la Difesa di tutti i nemici di 1 stadio." },
  344: { nome:"Proiettile Semi", tipo:"grass", cat:"fisico", potenza:25, accuratezza:100, pp:30, effetto:"moltiplica_turni_2_5", descrizione:"Colpisce 2-5 volte per turno." },
  345: { nome:"Fuoco Sacro", tipo:"fire", cat:"speciale", potenza:100, accuratezza:95, pp:5, effetto:"ustione_50", descrizione:"50% di probabilità di ustionare il bersaglio." },
  346: { nome:"Danza Spirale", tipo:"water", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_atk_1", descrizione:"Aumenta Attacco e Velocità dell'utente di 1 stadio." },
  347: { nome:"Pioggia Meteorica", tipo:"normal", cat:"fisico", potenza:60, accuratezza:100, pp:20, effetto:null, descrizione:"Infligge 1/8 PV extra il turno successivo." },
  348: { nome:"Grandine Rocciosa", tipo:"rock", cat:"fisico", potenza:50, accuratezza:90, pp:10, effetto:null, descrizione:"Colpisce entrambi i nemici in doppia battaglia." },
  349: { nome:"Tempesta di Sabbia", tipo:"rock", cat:"stato", potenza:0, accuratezza:0, pp:10, effetto:null, descrizione:"Attiva tempesta di sabbia per 5 turni." },
  350: { nome:"Tuono Sabbia", tipo:"ground", cat:"fisico", potenza:35, accuratezza:85, pp:15, effetto:"abbassa_vel_1", descrizione:"Abbassa la Velocità del bersaglio." },
  351: { nome:"Danza Spettro", tipo:"ghost", cat:"stato", potenza:0, accuratezza:0, pp:20, effetto:"alza_spa_1", descrizione:"Aumenta l'Attacco Speciale dell'utente di 1 stadio." },
  352: { nome:"Impulso Oscuro", tipo:"dark", cat:"speciale", potenza:80, accuratezza:100, pp:15, effetto:"confusione_20", descrizione:"20% di probabilità di confondere il bersaglio." },
  353: { nome:"Vendetta", tipo:"dark", cat:"fisico", potenza:70, accuratezza:100, pp:5, effetto:null, descrizione:"La potenza raddoppia se un compagno di squadra è svenuto." },
  354: { nome:"Colpo Basso 2", tipo:"fighting", cat:"fisico", potenza:40, accuratezza:100, pp:30, effetto:"colpo_critico_alto", descrizione:"Alta probabilità di colpo critico." },
};

if (typeof module !== 'undefined' && module.exports) module.exports = MOSSE_DB;
